"li t3,-1\n\t"
"li t2,-1\n\t"
"addi %[lw_cnt], %[lw_cnt], 2\n\t"
"loop1:\n\t"
"mul t3, t3, t2\n\t"
"addi %[mul_cnt], %[mul_cnt], 1\n\t"
"slli t1, t4, 1\n\t"
"addi %[others_cnt], %[others_cnt], 1\n\t"
"addi t1, t1 ,1\n\t"
"addi %[add_cnt], %[add_cnt],1\n\t"
"fcvt.d.w f2, t3\n\t"   
"fcvt.d.w f1, t1\n\t"  
"addi %[others_cnt], %[others_cnt], 2\n\t"
"fdiv.d f1, f2, f1\n\t" 
"addi %[div_cnt], %[div_cnt], 1\n\t"
"fadd.d  %[pi], %[pi], f1\n\t"
"addi %[add_cnt], %[add_cnt],1\n\t"
"addi t4, t4, 1\n\t"
"addi %[add_cnt], %[add_cnt],1\n\t"
"addi %[others_cnt], %[others_cnt], 1\n\t"
"blt t4, %[N], loop1\n\t"
